from tkinter import *
window = Tk()
window.title("Hello Strange!")
window.geometry("600x800")
window.config(bg="white")
frame1 = Frame(window, bg = "orange", height = 300, width = 700, cursor= "trek" )
frame2 = Frame(window, bg = "green", height = 300, width = 700, cursor= "tcross" )

button1 = Button(frame1, text = "Click Me once", bg = "red")
button2 = Button(frame2, text = "Click Me twice", bg = "blue")
button3 = Button(frame1, text = "Click Me thrice", fg = "green", bg = "yellow")
inp = (Label(window,bg = "yellow", text = "Tathagata"))
frame1.pack(side = TOP)
frame2.pack(side = BOTTOM)
button1.pack()
button2.pack()
button3.pack()
inp.pack()
window.mainloop()
